/* generated by unplugin-react-components */
export {}
declare global{
	const BubbleText: typeof import('./src/components/BubbleText/BubbleText')['BubbleText']
	const _layout: typeof import('./src/pages/user/_layout')['default']
}